apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: l20ftnoch-go-gitops
  description: This is GitOps manifest for l20ftnoch-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=l20ftnoch-go
    backstage.io/kubernetes-id: l20ftnoch-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: l20ftnoch-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:l20ftnoch-go
